/* =======================================================================
   CONTENT BLOCK for the Water in the World WAGOLL family.
   This is the ONLY place the wall text lives.

   Mark evidence in an example with {key|the phrase}, where key is one of
   the criterion keys in CRITERIA. Anything left unmarked stays black.

   ------------------------------------------------------------------
   CURRICULUM. Checked against the Victorian Curriculum 2.0 Geography
   Foundation to Level 10 scope and sequence.

   Geography's skills strand does NOT decompose into four parallel
   ladders the way History's "Using historical sources" does. Its
   sub-strands are inquiry (S01), collecting (S02), representing (S03),
   interpreting (S04), concluding and decision-making (S05-S06) and
   communicating (S07). The four rows of this wall are a teaching
   structure that draws across S02 to S05, and VC below records exactly
   which descriptor each rung is claiming. Do not read the rows as
   sub-strands, because they are not.

   Two consequences worth knowing:

   1. S04 (interpret and analyse data) and S05 (draw evidence-based
      conclusions) DO NOT EXIST below Levels 5 and 6. The Foundation to
      Level 4 rungs therefore claim fewer descriptors, exactly as the
      History wall does at the same bands. That is the curriculum, not
      an omission here.

   2. The unit sits on VC2HG8K01, K03 and K04. K03 is specifically
      "the distribution and variability of AUSTRALIA'S water resources",
      and this source is global, so the wall covers the scarcity and
      distribution half of the unit but not the Australian half. A
      second source is needed for that. See the note in the README.

   THE FIGURE IS OURS. The percentages are the United States Geological
   Survey's (public domain); the drawing is a classroom redraw generated
   by make-figure.mjs. The wall says so out loud because "who made this
   display, and why" is half the source analysis.
   ======================================================================= */

const WALL = {
  id: "geog-water",
  title: "Where the world's water is",
  expected: "Year 7",
  inquiry: "If the Earth is covered in water, how can anywhere run short of it?",
  foot: "<b>Data:</b> U.S. Geological Survey, &ldquo;Where is Earth's water?&rdquo;, after Shiklomanov, I. A. (1993), &ldquo;World fresh water resources,&rdquo; in Gleick, P. H. (ed.), <i>Water in Crisis</i>. USGS material is in the public domain. <b>The figure is a classroom redraw</b>, not a published graphic: it is generated by <code>make-figure.mjs</code> in this folder, and the panel proportions and the printed percentages come from the same numbers. The fourth slice of panel 3 is a remainder and is labelled as one. <b>Curriculum:</b> checked against the Victorian Curriculum 2.0 Geography F&ndash;10 scope and sequence. The unit sits on VC2HG8K01, K03 and K04; because this source is global, it covers the scarcity and distribution half of the unit and not the Australian half of K03."
};

const FACTS = [
  ["What it is", "A three-panel bar figure. Each panel takes one slice of the panel above it and breaks that slice open."],
  ["Where the numbers are from", "The United States Geological Survey's summary of global water storage, itself drawn from Shiklomanov's 1993 estimates."],
  ["Who drew it", "This classroom. The numbers are someone else's; the display is ours, and that is part of what there is to analyse."],
  ["What it measures", "Stores &mdash; how much water is sitting in each place at one moment. It does not measure flow."],
  ["The scale", "Global, and one moment in time. No country, no river, no year."],
  ["Known limits", "The figures are modelled estimates, not measurements. The smallest slice on the chart, rivers, is the one most people actually drink from."]
];

/* ink   — the colour on paper, all four above 4.5:1 on the wall's cream
   lamp  — the same criterion on the dark bar of the big-screen tool
   underline — the second channel, which is what survives a greyscale
               photocopy and a colour-blind reader */
const CRITERIA = [
  { key:"source",   row:"Data, origin &amp; purpose",       name:"Data, origin &amp; purpose",       glyph:"■",
    ink:"#176b87", lamp:"#6fc0da", underline:"solid" },
  { key:"context",  row:"Place, space &amp; scale",         name:"Place, space &amp; scale",         glyph:"▲",
    ink:"#357a46", lamp:"#74c288", underline:"dashed" },
  { key:"evidence", row:"Interconnection &amp; explanation", name:"Interconnection &amp; explanation", glyph:"●",
    ink:"#a34d1d", lamp:"#e89a63", underline:"dotted" },
  { key:"judge",    row:"Usefulness &amp; limitations",     name:"Usefulness &amp; limitations",     glyph:"◆",
    ink:"#744f91", lamp:"#bda0d8", underline:"double" },
];

const LEVELS = ["Grade 5","Year 6","Year 7","Year 8","Year 9","Year 10"];

const EXAMPLES = {
"Grade 5":
`This is a data picture about {source|where Earth's water is}. It shows that {source|96.5% of all water is in the ocean}. Only {source|2.5% is fresh water}. Most of the fresh water is {context|frozen in ice caps and glaciers}, and {context|almost all of the rest is underground}. Rivers hold {evidence|less than half of one per cent of the water on the surface}. That is why {evidence|a place can run short of water on a planet covered in it}. The picture is {judge|useful for showing how small the drinkable share is}, but it {judge|does not tell us where the shortages are}.`,

"Year 6":
`The source is a chart of {source|how the world's water is divided up}, drawn from figures published by {source|the United States Geological Survey}. It shows {source|96.5% of the world's water sitting in the oceans}. Only {source|2.5% of it is fresh water}. Of that fresh water, {context|68.7% is frozen in glaciers and ice caps} and {context|another 30.1% is under the ground}. That leaves {evidence|about 1.2% at the surface}. Rivers are {evidence|a tiny part even of that}. The fresh water is {evidence|spread so unevenly that some places have almost none}. The chart is {judge|useful for showing scale}, but it {judge|gives one moment and no change over time}.`,

"Year 7":
`The data source is {source|a set of global estimates of where the world's water is stored}, published by {source|the United States Geological Survey}. The chart itself is {source|a redraw made for this classroom}, and its purpose is {source|to show at a glance how little of the world's water people can actually use}. At a global scale, {context|96.5% of water is ocean}. Only {context|2.5% of it is fresh}. Within that fresh water, {context|the largest stores are polar ice and aquifers underground}, and both sit {context|far from where most people live}. The chart explains water scarcity as {evidence|a problem of where water is, not how much there is}. Surface fresh water is {evidence|about 1.2% of the fresh total}, and rivers are {evidence|a fraction of that again}. The source is {judge|very useful for showing scale}, because {judge|the three panels can be compared directly}. It cannot tell us {judge|which regions are short of water, or how the stores change from year to year}.`,

"Year 8":
`This is a global stock estimate: {source|a figure reporting how much water sits in each store at one moment}. The figures were compiled {source|by the United States Geological Survey, from surveys and modelling}. The chart was drawn {source|to be read quickly}, which flattens {source|a set of uncertain estimates into three clean panels}. At the global scale, {context|the oceans hold 96.5% of all water, and fresh water is 2.5% of it}. That fresh water is {context|shaped by latitude and by geology}: {context|ice at high latitudes, aquifers beneath particular rocks}. The chart supports the view that {evidence|scarcity is caused by where water sits and how fast it moves}, {evidence|not by how much of it exists}. Rivers hold {evidence|a tiny standing volume}, but they are {evidence|refilled many times a year, so they supply far more than their share of the chart suggests}. The figure is {judge|well supported for the broad proportions, which several independent compilations agree on}. I would ask {judge|how the estimates were made, how old they are, and whether a chart of stores suits something that flows}.`,

"Year 9":
`The figure is a secondary representation. It redraws {source|estimates that were themselves built from surveys, satellite data and modelling}, not {source|anything measured directly}. Its purpose is to teach, and {source|the three nested panels that make it teachable also make each one look more certain than it is}. Spatially, {context|the fresh water is concentrated where people are not, in the polar ice sheets and in deep aquifers}, so {context|the pattern of supply and the pattern of demand do not overlap}. The chart supports the view that {evidence|scarcity is a function of distribution, accessibility and rate of renewal}. A chart of stores conceals the last of those: {evidence|river water is a minute standing volume that turns over in days}, while {evidence|the ice is vast and effectively locked away}. The source is {judge|strong for proportion at a global scale, because independent compilations converge on the same figures}. It is {judge|weak for any question about a place, a year or a rate of change}, because {judge|it holds no time and no location at all}.`,

"Year 10":
`The chart is an argument as much as a description. Its explicit content is {source|a set of proportions attributed to the United States Geological Survey}. Its implicit claim is that {source|the right way to understand water is by comparing stores}. It is addressed {source|to a reader expected to be surprised by the third panel}. It works at {context|a single global scale, the scale at which distribution looks like destiny and at which every local intervention disappears}. It reflects a habit of thought that {context|treats the planet as a set of reservoirs to be counted}. Hydrologists accept the proportions {evidence|because separate compilations, built by different methods, converge on them}. They qualify what follows from them {evidence|because residence time, not volume, governs how much water is actually available}: {evidence|the ice is 68.7% of fresh water and supplies almost none of it}, while {evidence|rivers are a rounding error and supply a great deal}. Overall the figure is {judge|strong evidence for global proportion and misleading evidence for availability}. Its strength is {judge|that it makes an abstract comparison instantly legible}; its limits are {judge|that it has no time axis, no place, no measure of renewal, and no sign of how uncertain the underlying estimates are}.`
};

const EXPLANATIONS = {
"Grade 5": {
  source:   "Names what the source is and reads two figures straight off it.",
  context:  "Says where the fresh water is: in ice, and underground.",
  evidence: "Connects the size of the river slice to the idea of running short.",
  judge:    "Gives one use and one limit."
},
"Year 6": {
  source:   "Names the type of source and who published the figures behind it.",
  context:  "Reads the second panel and gives both of its large stores.",
  evidence: "Links the small surface share to uneven distribution.",
  judge:    "Recognises usefulness for scale and names the missing dimension: time."
},
"Year 7": {
  source:   "Separates the published data from the classroom redraw, then states the purpose of the display.",
  context:  "Describes the global pattern and notes that the big stores are far from people.",
  evidence: "Explains scarcity as a distribution problem and supports it with the panel figures.",
  judge:    "Concludes that the comparison is the useful part, then bounds the claim with two limits."
},
"Year 8": {
  source:   "Describes what kind of measurement this is — a stock at one moment — and how the display simplifies it.",
  context:  "Describes distribution by latitude and geology rather than just naming the stores.",
  evidence: "Introduces rate of renewal, which is the thing the chart cannot show.",
  judge:    "Notes independent agreement, then asks targeted questions about method, age and chart type."
},
"Year 9": {
  source:   "Explains that the figure is two steps from measurement, and that its clarity is bought with apparent certainty.",
  context:  "Explains the mismatch between the pattern of supply and the pattern of demand.",
  evidence: "Analyses scarcity through three named factors and shows which one the display hides.",
  judge:    "Ranks the claim: strong for proportion, weak for place, year and change."
},
"Year 10": {
  source:   "Analyses the implicit argument of the display and the reader it assumes.",
  context:  "Uses scale to explain what the figure makes visible and what it erases.",
  evidence: "Exposes why the proportions are accepted but the conclusions are not.",
  judge:    "Weighs a strength against four limitations and separates two claims of different strength."
}
};

const CONTINUUM = {
source:{
 "Grade 5":"I can name a geographical source and read information from it.",
 "Year 6":"I can identify what kind of data a source shows and where it came from.",
 "Year 7":"I can identify the origin, content and purpose of geographical data.",
 "Year 8":"I can describe the origin, content and purpose of geographical data, including how it was collected.",
 "Year 9":"I can explain how geographical data was produced and how that shapes what it shows.",
 "Year 10":"I can analyse the explicit content and the implicit argument of a geographical representation."},
context:{
 "Grade 5":"I can say where something is.",
 "Year 6":"I can describe a pattern of distribution.",
 "Year 7":"I can describe distribution across space and identify the scale a source works at.",
 "Year 8":"I can describe spatial distribution and explain what shapes it.",
 "Year 9":"I can explain spatial patterns across scales and account for the differences between them.",
 "Year 10":"I can analyse how the scale chosen changes what a representation shows and hides."},
evidence:{
 "Grade 5":"I can connect two things shown in a source.",
 "Year 6":"I can describe how one geographical thing affects another.",
 "Year 7":"I can explain an interconnection using evidence from the source.",
 "Year 8":"I can explain interconnections between environmental processes and human use.",
 "Year 9":"I can analyse interconnections and identify the processes that produce a pattern.",
 "Year 10":"I can evaluate competing explanations of a geographical pattern and account for why they differ."},
judge:{
 "Grade 5":"I can say one thing a source is good for and one thing it cannot tell me.",
 "Year 6":"I can recognise that some sources are more useful than others.",
 "Year 7":"I can draw conclusions about the usefulness of geographical data.",
 "Year 8":"I can question the accuracy and reliability of data, including how and when it was collected.",
 "Year 9":"I can identify the accuracy, usefulness and limitations of a source and rank my claims accordingly.",
 "Year 10":"I can analyse the usefulness and limitations of a representation, including what its form conceals."},
};

const SHEET_IMAGE = "water-distribution.png";

/* What the big-screen tool puts in the left-hand panel. */
const SOURCE_PANEL = {
  kind: "image",
  file: SHEET_IMAGE,
  ar:   "1600/1320",
  alt:  "Three stacked bar charts. All Earth's water, 96.5% ocean. All fresh water: 68.7% frozen, 30.1% groundwater, 1.2% surface. Surface fresh water: 73.1% ice and snow, 20.9% lakes, 5.5% other, 0.49% rivers.",
  missing: "The figure did not load.<br>Keep <b>water-distribution.png</b> in the same folder as this page.",
  whole: { label:"All three panels",
    text:"Each panel opens up one slice of the panel above it. The bar stays the same width every time, which is what makes the last panel land." }
};

/* Clickable regions on water-distribution.png, as percentages of the image. */
const HOTSPOTS = [
 { x:4,  y:7,  w:92, h:26, label:"Panel 1 — all the water",
   text:"Every drop on the planet. 96.5% of it is salt water in the oceans, so everything people drink, grow food with and wash in comes out of the pale sliver on the right." },
 { x:4,  y:36, w:92, h:27, label:"Panel 2 — the fresh water",
   text:"The pale sliver, opened up. Almost seven tenths of the world's fresh water is frozen, and almost all the rest is underground. Both are hard to reach." },
 { x:4,  y:65, w:92, h:27, label:"Panel 3 — the surface water",
   text:"What is left. Rivers are 0.49% of this panel, which is 0.49% of 1.2% of 2.5% of all the water there is — and rivers are where most of the world's cities get their water." },
 { x:4,  y:94, w:70, h:5.5, label:"Where the numbers came from",
   text:"The line that makes this analysable. The percentages are the U.S. Geological Survey's, after Shiklomanov 1993. The drawing is ours. Estimates, not measurements, and more than thirty years old." }
];


/* ---------------------------------------------------------------------------
   The rungs below Grade 5. Two bands rather than five year levels, to match the
   way the curriculum bands the primary years.
   --------------------------------------------------------------------------- */

const EARLY_LEVELS = ["Foundation to Level 2", "Levels 3 and 4"];

const EARLY_EXAMPLES = {
 "Foundation to Level 2":
`This picture is about water. Most of it is {source|salty}. A little bit is {source|fresh}. Most fresh water is {context|ice}.`,

 "Levels 3 and 4":
`The picture shows {source|where all the water on Earth is}. About {source|97 parts out of 100 is salty}. Only {source|3 parts are fresh}. Most of the fresh water is {context|frozen in ice}. A lot of the rest is {context|under the ground}. Rivers and lakes hold {evidence|only a tiny bit}. But that is {evidence|where most people get their water}.`
};

const EARLY_EXPLANATIONS = {
 "Foundation to Level 2": {
   source:  "Names what the source shows and reads the biggest thing off it.",
   context: "Says where the fresh water is." },
 "Levels 3 and 4": {
   source:  "Reads the proportions off the chart and puts them in whole numbers.",
   context: "Describes the distribution: ice at the poles, and underground.",
   evidence:"Connects the size of a slice to how people actually get water." }
};

/* No VC codes here on purpose — see the header. */
const VC = {
 "Foundation to Level 2": [
  ["VC2HG2S02","collect, sort and record information and data from observations, including from fieldwork and maps"],
  ["VC2HG2S03","represent and describe the information and data from observations in different formats, including sketches and labelled maps or photographs"]],
 "Levels 3 and 4": [
  ["VC2HG4S02","locate, collect and record information and data from a range of sources, including from fieldwork, maps, photographs and graphs"],
  ["VC2HG4S03","represent and analyse information and data collected in different formats"]],
 "Grade 5": [
  ["VC2HG6S02","locate, collect and organise information and data from primary and secondary sources, including from fieldwork"],
  ["VC2HG6S04","interpret and analyse information and data in a range of formats to identify and describe patterns and trends, or to infer relationships"],
  ["VC2HG6S05","develop evidence-based conclusions on the management of places using the concepts of place, interconnection, environment and sustainability"]],
 "Year 6": [
  ["VC2HG6S02","locate, collect and organise information and data from primary and secondary sources, including from fieldwork"],
  ["VC2HG6S04","interpret and analyse information and data in a range of formats to identify and describe patterns and trends, or to infer relationships"],
  ["VC2HG6S05","develop evidence-based conclusions on the management of places using the concepts of place, interconnection, environment and sustainability"]],
 "Year 7": [
  ["VC2HG8S02","collect, organise and process information and data from primary and secondary sources, including fieldwork, and using geospatial technologies and digital tools as appropriate"],
  ["VC2HG8S03","represent and describe information and data using a range of formats, including maps constructed with geospatial technologies"],
  ["VC2HG8S04","interpret and analyse information and data to identify similarities and differences and explain patterns, relationships and trends"],
  ["VC2HG8S05","consider ethical values and draw evidence-based conclusions based on the evaluation of the information and data on a geographical phenomenon, issue or challenge using the concepts of space, change, interconnection and environment"]],
 "Year 8": [
  ["VC2HG8S02","collect, organise and process information and data from primary and secondary sources, including fieldwork, and using geospatial technologies and digital tools as appropriate"],
  ["VC2HG8S03","represent and describe information and data using a range of formats, including maps constructed with geospatial technologies"],
  ["VC2HG8S04","interpret and analyse information and data to identify similarities and differences and explain patterns, relationships and trends"],
  ["VC2HG8S05","consider ethical values and draw evidence-based conclusions based on the evaluation of the information and data on a geographical phenomenon, issue or challenge using the concepts of space, change, interconnection and environment"]],
 "Year 9": [
  ["VC2HG10S02","collect, process and compare information and data from primary and secondary sources, including fieldwork and secondary research materials, using geospatial technologies and digital tools as appropriate"],
  ["VC2HG10S03","represent and analyse information and data using a range of formats, including graphs and maps constructed with geospatial technologies"],
  ["VC2HG10S04","interpret and evaluate information and data to make generalisations and predictions, analyse patterns and trends, infer relationships and make forecasts"],
  ["VC2HG10S05","consider ethical values and perspectives to justify conclusions related to a phenomenon, issue or challenge using geographical concepts"]],
 "Year 10": [
  ["VC2HG10S02","collect, process and compare information and data from primary and secondary sources, including fieldwork and secondary research materials, using geospatial technologies and digital tools as appropriate"],
  ["VC2HG10S03","represent and analyse information and data using a range of formats, including graphs and maps constructed with geospatial technologies"],
  ["VC2HG10S04","interpret and evaluate information and data to make generalisations and predictions, analyse patterns and trends, infer relationships and make forecasts"],
  ["VC2HG10S05","consider ethical values and perspectives to justify conclusions related to a phenomenon, issue or challenge using geographical concepts"]]
};

const VC_NOTE = "Checked against the Victorian Curriculum 2.0 Geography F–10 scope and sequence. Geography's skills sub-strands are not four parallel ladders, so the four rows of this wall draw across S02 to S05 rather than matching one sub-strand each. Interpreting (S04) and concluding (S05) do not exist below Levels 5 and 6, which is why the early rungs claim fewer descriptors. The unit itself sits on VC2HG8K01, K03 and K04.";

const BUMP = {
 "Foundation to Level 2": {
   new:"You say what the picture is about, and you read the biggest part off it.",
   background:"That a picture can stand for a whole amount of something, not just show a thing." },
 "Levels 3 and 4": {
   new:"You put numbers to the parts, and you say where the water actually is.",
   background:"That a percentage is a share of a whole, and that the whole changes from panel to panel." },
 "Grade 5": {
   new:"Three things switch on at once: you use the figures exactly, you connect a small slice to a real consequence, and you say what the source cannot do.",
   background:"That a source can be strong evidence for one thing and weak evidence for another at the same time." },
 "Year 6": {
   new:"You name who published the figures, and you read the second panel properly instead of summarising it.",
   background:"That someone collected these numbers, and that the chart is a display of them rather than the thing itself." },
 "Year 7": {
   new:"You separate the published data from the display made out of it, and you say why the display was made.",
   background:"That the same numbers can be drawn in ways that argue different things." },
 "Year 8": {
   new:"You name what kind of measurement it is — a store at one moment — and you bring in how fast water is replaced.",
   background:"That a river holding very little water can still supply a lot, because it refills. This is residence time." },
 "Year 9": {
   new:"You explain why several compilations agreeing is stronger than one, and you rank your claims by how well the source supports them.",
   background:"What independent estimates are, and that the clarity of a graphic can hide how uncertain its numbers are." },
 "Year 10": {
   new:"You read the argument the chart is making underneath its numbers, and you explain what choosing a global scale erases.",
   background:"That the form of a representation — stores, one moment, one scale — is itself a claim about what matters." }
};

/* Tier 3 = the subject's own words, which need a definition.
   Tier 2 = general academic words, which need a plainer synonym.
   Matched case-insensitively on whole words wherever they appear. */
const GLOSS = {
 tier3: {
  "fresh water":"Water without much salt in it. The kind people can drink and grow crops with.",
  "groundwater":"Water held in the spaces inside soil and rock, under the ground.",
  "aquifer":"A layer of rock that holds water and lets it move through, like a sponge made of stone.",
  "glacier":"A river of ice that moves very slowly downhill.",
  "glaciers":"Rivers of ice that move very slowly downhill.",
  "ice cap":"A thick dome of ice covering land near a pole.",
  "ice caps":"Thick domes of ice covering land near the poles.",
  "soil moisture":"Water held in the soil itself, between the grains.",
  "residence time":"How long a drop of water stays in one place before it moves on. Days in a river, thousands of years in ice.",
  "store":"A place where water sits: the ocean, an ice sheet, an aquifer, a lake.",
  "stock":"How much of something there is at one moment, rather than how fast it moves.",
  "scarcity":"Not having enough of something for the people who need it.",
  "distribution":"How something is spread out across a place.",
  "hydrologist":"A scientist who studies water: where it is, how it moves and how much there is.",
  "hydrologists":"Scientists who study water: where it is, how it moves and how much there is.",
  "compilation":"A set of figures gathered together from many separate studies.",
  "modelling":"Working out a number using a calculation, when you cannot measure the thing directly.",
  "scale":"How big an area you are looking at: a river, a country, the whole world.",
  "per cent":"Out of every hundred."
 },
 tier2: {
  "estimate":"a careful guess",
  "estimates":"careful guesses",
  "proportion":"how big one part is compared with the whole",
  "proportions":"how big the parts are compared with the whole",
  "available":"able to be used",
  "accessible":"able to be reached",
  "conceals":"hides",
  "converge":"point the same way",
  "independent":"separate · not connected",
  "purpose":"the reason it was made",
  "represent":"stand for",
  "representation":"something that stands for the real thing",
  "uneven":"not the same everywhere",
  "qualify":"limit · add conditions to",
  "identify":"name · point out",
  "describe":"say what it is like",
  "analyse":"break it down and examine it",
  "evaluate":"judge how good it is",
  "supports":"backs up",
  "suggests":"hints at",
  "governs":"decides · controls"
 }
};

/* The continuum said the way a student would say it. */
const KID = {
 "Foundation to Level 2": { band:"Foundation to Level 2", lines:[
   "I can collect what I notice and write it down.",
   "I can draw or label what I found."]},
 "Levels 3 and 4": { band:"Levels 3 and 4", lines:[
   "I can find information and data and record it.",
   "I can show the data and pull it apart."]},
 "Grade 5": { band:"Levels 5 and 6", lines:[
   "I can find and sort information from primary and secondary sources.",
   "I can read data and describe the patterns in it.",
   "I can draw a conclusion from the evidence, using place and interconnection."]},
 "Year 6": { band:"Levels 5 and 6", lines:[
   "I can find and sort information from primary and secondary sources.",
   "I can read data and describe the patterns in it.",
   "I can draw a conclusion from the evidence, using place and interconnection."]},
 "Year 7": { band:"Levels 7 and 8", lines:[
   "I can collect and organise data from primary and secondary sources.",
   "I can present data and describe what it shows.",
   "I can find similarities and differences, and explain the patterns and trends.",
   "I can weigh up the data and draw a conclusion from it, using space, change, interconnection and environment."]},
 "Year 8": { band:"Levels 7 and 8", lines:[
   "I can collect and organise data from primary and secondary sources.",
   "I can present data and describe what it shows.",
   "I can find similarities and differences, and explain the patterns and trends.",
   "I can weigh up the data and draw a conclusion from it, using space, change, interconnection and environment."]},
 "Year 9": { band:"Levels 9 and 10", lines:[
   "I can collect data from several sources and compare them.",
   "I can present data and pull the patterns apart.",
   "I can judge the data, work out what follows from it, and predict what happens next.",
   "I can use values and other people's perspectives to justify my conclusion."]},
 "Year 10": { band:"Levels 9 and 10", lines:[
   "I can collect data from several sources and compare them.",
   "I can present data and pull the patterns apart.",
   "I can judge the data, work out what follows from it, and predict what happens next.",
   "I can use values and other people's perspectives to justify my conclusion."]}
};


/* ---------------------------------------------------------------------------
   The paragraph frame. The four steps are the four criteria in the order you
   write them, so reading down the wall is the same as writing the paragraph.
   --------------------------------------------------------------------------- */

const FRAME = {
  name: "D · P · I · U",
  blurb: "The four steps are the four criteria, in the order you write them. Reading down the wall is the same as writing the paragraph.",
  steps: [
    { key:"source", letter:"D", title:"Data",
      job:"Say what the data is, who produced it, and why this display was made.",
      guide:"Two different things get named here: the figures, and the display built out of them. Name both. A chart is somebody's choice about how to show a number.",
      warn:"This is a graph about water.",
      warnWhy:"That is the topic, not the source. No origin, no content, no purpose.",
      stems:["The data is ___, published by ___.",
             "The display itself is ___, made to ___.",
             "It reports ___ at ___."] },

    { key:"context", letter:"P", title:"Place &amp; scale",
      job:"Say where things are, and at what scale you are looking.",
      guide:"Scale is a choice, and it decides what you can see. A global figure hides every country in it. Say which scale this works at, and what that scale leaves out.",
      warn:"Water is everywhere in the world.",
      warnWhy:"No pattern and no scale. Where is it, and how big is the area you are describing?",
      stems:["At a ___ scale, ___ is concentrated in ___.",
             "The largest stores sit in ___, far from ___.",
             "At this scale ___ disappears."] },

    { key:"evidence", letter:"I", title:"Interconnection",
      job:"Explain how one thing is connected to another, using the figures.",
      guide:"An explanation needs its number attached with “because”. The interesting connections here are the ones the chart cannot show — how fast a store refills, not just how big it is.",
      warn:"There is not much fresh water so people run out.",
      warnWhy:"You have named a result without the process. What connects the amount to the shortage?",
      stems:["___ explains ___ because ___.",
             "Although ___ holds only ___, it supplies ___ because ___.",
             "The pattern of supply and the pattern of demand ___."] },

    { key:"judge", letter:"U", title:"Usefulness",
      job:"Judge what the source is good for, then say plainly what it cannot settle.",
      guide:"Useful for what? Name the claim. Then bound it. A limit is not an apology — it is half of the judgement.",
      warn:"This source is very useful and reliable.",
      warnWhy:"Useful for which claim? A judgement with nothing attached and no limit is not a judgement.",
      stems:["___ is useful for ___ because ___.",
             "However, it cannot tell us ___.",
             "It is strong evidence for ___, but misleading evidence for ___."] },
  ]
};

const VERBS = {
  use: [
    { w:"shows",        note:"points at the data" },
    { w:"reports",      note:"points at the data" },
    { w:"describes",    note:"adds detail" },
    { w:"represents",   note:"what the display does" },
    { w:"explains",     note:"gives a reason" },
    { w:"interprets",   note:"reads meaning from data" },
    { w:"suggests",     note:"reads meaning from data" },
    { w:"conceals",     note:"names what the display hides" },
    { w:"governs",      note:"names what controls something" },
    { w:"qualifies",    note:"limits a claim" },
    { w:"converge",     note:"separate sources agreeing" }
  ],
  avoid: [
    { w:"proves",  why:"one figure rarely proves anything on its own" },
    { w:"talks about", why:"a chart does not talk. Say what it shows." },
    { w:"is about", why:"names the topic, not what the source does" }
  ]
};


/* ---------------------------------------------------------------------------
   PEEL and TEEL. Not a different paragraph — the same moves under the names
   students meet in English, mapped onto the same criterion keys so that a
   student's writing survives switching frames.

   P and T are the same move. Both are here because different classes are
   taught different letters, and arguing about the letter helps nobody.
   --------------------------------------------------------------------------- */

const FRAMES = [FRAME,
 { name:"P · E · E · L",
   blurb:"The same four moves under the letters you use in English. Your writing carries across if you switch.",
   steps:[
    { key:FRAME.steps[0].key, letter:"P", title:"Point",
      job:FRAME.steps[0].job, guide:FRAME.steps[0].guide,
      warn:FRAME.steps[0].warn, warnWhy:FRAME.steps[0].warnWhy,
      stems:FRAME.steps[0].stems },
    { key:FRAME.steps[2].key, letter:"E", title:"Evidence",
      job:FRAME.steps[2].job, guide:FRAME.steps[2].guide,
      warn:FRAME.steps[2].warn, warnWhy:FRAME.steps[2].warnWhy,
      stems:FRAME.steps[2].stems },
    { key:FRAME.steps[1].key, letter:"E", title:"Explain",
      job:FRAME.steps[1].job, guide:FRAME.steps[1].guide,
      warn:FRAME.steps[1].warn, warnWhy:FRAME.steps[1].warnWhy,
      stems:FRAME.steps[1].stems },
    { key:FRAME.steps[3].key, letter:"L", title:"Link",
      job:FRAME.steps[3].job, guide:FRAME.steps[3].guide,
      warn:FRAME.steps[3].warn, warnWhy:FRAME.steps[3].warnWhy,
      stems:FRAME.steps[3].stems }]},
 { name:"T · E · E · L",
   blurb:"The same as PEEL, with Topic sentence in place of Point. Your writing carries across if you switch.",
   steps:[
    { key:FRAME.steps[0].key, letter:"T", title:"Topic sentence",
      job:FRAME.steps[0].job, guide:FRAME.steps[0].guide,
      warn:FRAME.steps[0].warn, warnWhy:FRAME.steps[0].warnWhy,
      stems:FRAME.steps[0].stems },
    { key:FRAME.steps[2].key, letter:"E", title:"Evidence",
      job:FRAME.steps[2].job, guide:FRAME.steps[2].guide,
      warn:FRAME.steps[2].warn, warnWhy:FRAME.steps[2].warnWhy,
      stems:FRAME.steps[2].stems },
    { key:FRAME.steps[1].key, letter:"E", title:"Explain",
      job:FRAME.steps[1].job, guide:FRAME.steps[1].guide,
      warn:FRAME.steps[1].warn, warnWhy:FRAME.steps[1].warnWhy,
      stems:FRAME.steps[1].stems },
    { key:FRAME.steps[3].key, letter:"L", title:"Link",
      job:FRAME.steps[3].job, guide:FRAME.steps[3].guide,
      warn:FRAME.steps[3].warn, warnWhy:FRAME.steps[3].warnWhy,
      stems:FRAME.steps[3].stems }]}
];

/* Translations for this unit's own tier-3 words, in the shape eal.js uses, so
   the tool treats a unit word and a shared word identically. The shared
   source-analysis words are NOT repeated here — they live in eal.js and only
   there. Machine-drafted, unreviewed, and labelled as such on screen. */
const TIER3_T = {
  "fresh water": {"zh-Hans": "淡水", "zh-Hant": "淡水", "vi": "nước ngọt", "ar": "مياه عذبة", "fa": "آب شیرین", "ur": "میٹھا پانی", "ml": "ശുദ്ധജലം", "am": "ንጹህ ውሃ"},
  "groundwater": {"zh-Hans": "地下水", "zh-Hant": "地下水", "vi": "nước ngầm", "ar": "مياه جوفية", "fa": "آب زیرزمینی", "ur": "زیرِ زمین پانی", "ml": "ഭൂഗർഭജലം", "am": "የከርሰ ምድር ውሃ"},
  "aquifer": {"zh-Hans": "含水层", "zh-Hant": "含水層", "vi": "tầng ngậm nước", "ar": "طبقة مياه جوفية", "fa": "سفره آب زیرزمینی", "ur": "آبی تہہ", "ml": "ജലസംഭരണ പാളി", "am": "የውሃ ንብርብር"},
  "glacier": {"zh-Hans": "冰川", "zh-Hant": "冰川", "vi": "sông băng", "ar": "نهر جليدي", "fa": "یخچال طبیعی", "ur": "گلیشیئر", "ml": "ഹിമാനി", "am": "የበረዶ ወንዝ"},
  "glaciers": {"zh-Hans": "冰川", "zh-Hant": "冰川", "vi": "các sông băng", "ar": "أنهار جليدية", "fa": "یخچال‌های طبیعی", "ur": "گلیشیئرز", "ml": "ഹിമാനികൾ", "am": "የበረዶ ወንዞች"},
  "ice cap": {"zh-Hans": "冰盖", "zh-Hant": "冰蓋", "vi": "chỏm băng", "ar": "قلنسوة جليدية", "fa": "کلاهک یخی", "ur": "برفانی ٹوپی", "ml": "ഹിമപാളി", "am": "የበረዶ ክዳን"},
  "ice caps": {"zh-Hans": "冰盖", "zh-Hant": "冰蓋", "vi": "các chỏm băng", "ar": "قلنسوات جليدية", "fa": "کلاهک‌های یخی", "ur": "برفانی ٹوپیاں", "ml": "ഹിമപാളികൾ", "am": "የበረዶ ክዳኖች"},
  "soil moisture": {"zh-Hans": "土壤水分", "zh-Hant": "土壤水分", "vi": "độ ẩm đất", "ar": "رطوبة التربة", "fa": "رطوبت خاک", "ur": "مٹی کی نمی", "ml": "മണ്ണിലെ ഈർപ്പം", "am": "የአፈር እርጥበት"},
  "residence time": {"zh-Hans": "滞留时间", "zh-Hant": "滯留時間", "vi": "thời gian lưu", "ar": "زمن المكوث", "fa": "زمان ماند", "ur": "قیام کا دورانیہ", "ml": "വാസകാലം", "am": "የቆይታ ጊዜ"},
  "store": {"zh-Hans": "储量", "zh-Hant": "儲量", "vi": "nơi chứa", "ar": "مخزن", "fa": "انبار", "ur": "ذخیرہ", "ml": "സംഭരണി", "am": "ማከማቻ"},
  "stock": {"zh-Hans": "存量", "zh-Hant": "存量", "vi": "lượng dự trữ", "ar": "مخزون", "fa": "موجودی", "ur": "ذخیرہ", "ml": "ശേഖരം", "am": "ክምችት"},
  "scarcity": {"zh-Hans": "稀缺", "zh-Hant": "稀缺", "vi": "sự khan hiếm", "ar": "ندرة", "fa": "کمیابی", "ur": "قلت", "ml": "ദൗർലഭ്യം", "am": "እጥረት"},
  "distribution": {"zh-Hans": "分布", "zh-Hant": "分布", "vi": "sự phân bố", "ar": "توزيع", "fa": "پراکنش", "ur": "تقسیم", "ml": "വിതരണം", "am": "ስርጭት"},
  "hydrologist": {"zh-Hans": "水文学家", "zh-Hant": "水文學家", "vi": "nhà thủy văn học", "ar": "عالم هيدرولوجيا", "fa": "آب‌شناس", "ur": "ماہرِ آبیات", "ml": "ജലശാസ്ത്രജ്ഞൻ", "am": "የውሃ ተመራማሪ"},
  "hydrologists": {"zh-Hans": "水文学家", "zh-Hant": "水文學家", "vi": "các nhà thủy văn học", "ar": "علماء الهيدرولوجيا", "fa": "آب‌شناسان", "ur": "ماہرینِ آبیات", "ml": "ജലശാസ്ത്രജ്ഞർ", "am": "የውሃ ተመራማሪዎች"},
  "compilation": {"zh-Hans": "汇编", "zh-Hant": "彙編", "vi": "bản tổng hợp", "ar": "تجميع", "fa": "گردآوری", "ur": "تالیف", "ml": "സമാഹാരം", "am": "ስብስብ"},
  "modelling": {"zh-Hans": "建模", "zh-Hant": "建模", "vi": "mô hình hóa", "ar": "نمذجة", "fa": "مدل‌سازی", "ur": "ماڈلنگ", "ml": "മാതൃകാ നിർമ്മാണം", "am": "ሞዴል ማድረግ"},
  "scale": {"zh-Hans": "尺度", "zh-Hant": "尺度", "vi": "quy mô", "ar": "مقياس", "fa": "مقیاس", "ur": "پیمانہ", "ml": "തോത്", "am": "መጠን"},
  "per cent": {"zh-Hans": "百分之", "zh-Hant": "百分之", "vi": "phần trăm", "ar": "في المائة", "fa": "درصد", "ur": "فیصد", "ml": "ശതമാനം", "am": "በመቶ"}
};
